/**
 * Shared form placeholders and select prompts — reuse across modules for consistent UX.
 * Optional fields: include "(optional)" in the placeholder text.
 */
export const PH = {
  personName: 'e.g. Rahul Sharma',
  companyName: 'e.g. Acme Logistics Pvt Ltd',
  customerName: 'e.g. Rahul Sharma',
  email: 'e.g. rahul@example.com',
  emailOptional: 'e.g. rahul@example.com (optional)',
  phone: 'e.g. +91 9876543210',
  phoneOptional: 'e.g. +91 9876543210 (optional)',
  vehiclePlate: 'e.g. AP09AB1234',
  orderInternalId: 'e.g. ORD-2026-0001',
  addressLine: 'e.g. 12 MG Road, Bangalore',
  addressLineOptional: 'e.g. 12 MG Road, Bangalore (optional)',
  street2Optional: 'e.g. Floor 3 (optional)',
  notesOptional: 'Add special instructions (optional)',
  descriptionOptional: 'Brief description (optional)',
  uuidOptional: 'e.g. 550e8400-e29b-41d4-a716-446655440000 (optional)',
  driverLicense: 'e.g. DL1420110012345',
  driverRefOptional: 'Driver id or uuid (optional)',
  vehicleMake: 'e.g. Tata',
  vehicleModel: 'e.g. Ace',
  vehicleYearOptional: 'e.g. 2024 (optional)',
  vehicleTrimOptional: 'e.g. Gold (optional)',
  vehicleType: 'e.g. LCV',
  vin: 'e.g. MA1RE2SZXPA123456',
  metaJsonOptional: 'e.g. {"key":"value"} (optional)',
  vendorTypeOptional: 'e.g. transporter (optional)',
  contactTypeOptional: 'e.g. contact (optional)',
  contactTitleOptional: 'e.g. Fleet Manager (optional)',
  cityOptional: 'e.g. Bangalore (optional)',
  provinceOptional: 'e.g. Karnataka (optional)',
  postalOptional: 'e.g. 560001 (optional)',
  countryOptional: 'e.g. IN (optional)',
  latOptional: 'e.g. 12.9716 (optional)',
  lngOptional: 'e.g. 77.5946 (optional)',
  placeTypeOptional: 'e.g. warehouse (optional)',
  entityTypeOptional: 'e.g. hub (optional)',
  statusTextOptional: 'e.g. active (optional)',
  slugOptional: 'e.g. acme-logistics (optional)',
  apiKeyName: 'e.g. Production TMS integration',
  groupName: 'e.g. Warehouse managers',
  password: 'e.g. At least 8 characters',
  loginIdentity: 'e.g. rahul@example.com or +91 9876543210',
  scheduledAtTitle: 'Pick local date and time for the stop',
  trackingNumber: 'e.g. TRK-7829341',
  trackingTypeOptional: 'e.g. parcel (optional)',
  extensionTypeOptional: 'e.g. webhook (optional)',
  extensionName: 'e.g. Slack notifications',
  customFieldEntityOptional: 'e.g. order, driver, vehicle (optional)',
  customFieldName: 'e.g. POD photo URL',
  customFieldId: 'e.g. cf_01HXYZ...',
  entityId: 'e.g. ord_01HXYZ...',
  entityTypeValueOptional: 'e.g. order (optional)',
  customFieldValueOptional: 'e.g. Yes, 42, 2026-03-26 (optional)',
  scheduleName: 'e.g. Bangalore morning dispatch',
  scheduleTitle: 'e.g. Load pickup — WH-1',
  scheduleTypeOptional: 'e.g. recurring (optional)',
  scheduleId: 'e.g. sch_01HXYZ...',
  constraintTypeOptional: 'e.g. max_hours (optional)',
  constraintValueOptional: 'e.g. 8 (optional)',
  limitOptional: 'e.g. 10 (optional)',
  ruleTypeOptional: 'e.g. hard (optional)',
  metaPlainOptional: 'e.g. {"max":10} or notes (optional)',
  isoStartOptional: 'e.g. 2026-03-20T09:00:00Z (optional)',
  isoEndOptional: 'e.g. 2026-03-20T17:00:00Z (optional)',
  dayOfWeekOptional: 'e.g. monday (optional)',
  issueTitleOptional: 'e.g. Flat tire on NH44 (optional)',
  issueReportOptional: 'Describe the incident (optional)',
  issueCategoryOptional: 'e.g. mechanical (optional)',
  issueTypeOptional: 'e.g. breakdown (optional)',
  issuePriorityOptional: 'e.g. high (optional)',
  issueStatusOptional: 'e.g. open (optional)',
  tagsCsvOptional: 'e.g. urgent, highway (optional)',
  jsonLocationOptional: 'e.g. {"lat":12.97,"lng":77.59} (optional)',
  fuelVolumeOptional: 'e.g. 45.5 (optional)',
  fuelOdometerOptional: 'e.g. 45230 (optional)',
  fuelAmountOptional: 'e.g. 3200 (optional)',
  fuelCurrencyOptional: 'e.g. INR (optional)',
  metricUnitOptional: 'e.g. litre or gallon (optional)',
  fuelReportOptional: 'Trip notes or station name (optional)',
  vehicleColorOptional: 'e.g. White (optional)',
  vehicleMetaNotesOptional: 'Add vehicle notes (optional)',
  searchOrders: 'e.g. ORD-2026-0001 or customer name',
  searchDrivers: 'e.g. DL1420110012345 or driver id',
  searchVehicles: 'e.g. AP09AB1234 or vehicle id',
  searchVendor: 'e.g. Rahul@example.com, vendor name, or uuid',
  searchContacts: 'e.g. +91 9876543210, name, or uuid',
  searchPlaces: 'e.g. MG Road, Bangalore, or phone',
  searchIssues: 'e.g. flat tire, issue id, or title',
  searchFuelReports: 'e.g. driver id, report id, or notes',
  searchFleets: 'e.g. North zone fleet',
  searchEntities: 'e.g. hub name or entity id',
  searchZones: 'e.g. South Bangalore',
  searchServiceAreas: 'e.g. CBD Bengaluru',
  serviceAreaName: 'e.g. CBD Bengaluru',
  zoneName: 'e.g. South Bangalore',
  fleetName: 'e.g. North zone fleet',
  entityName: 'e.g. WH-Hub Indiranagar',
  placeNameOptional: 'e.g. WH Indiranagar (optional)',
  searchTrackingNumbers: 'e.g. TRK-7829341',
  searchTrackingStatuses: 'e.g. in_transit',
  trackingStatusName: 'e.g. in_transit',
  searchCompanies: 'e.g. Acme Logistics',
  searchTemplates: 'e.g. weekly roster',
} as const;

/** First `<option>` label for native `<select>`s (pair with `value=""` and `disabled` where needed). */
export const SELECT_PH = {
  status: 'Select status',
  orderType: 'Select order type',
  priority: 'Select priority',
  fieldType: 'Select field type',
  metricUnit: 'Select unit',
  dateRange: 'Select date range',
  /** List/filter selects */
  type: 'Select type',
} as const;
